### PR TITLE
Badge alignment.

### PR DESCRIPTION
**Pull request by krishnashenoy123**
#113 
Screenshot from 2021-01-29 23-18-05

### CODE REVIEW

**Review by 18praneeth — APPROVED** [review]

**Comment by 18praneeth** [comment]
Looks good to me 🙌 
@swasthikcnayak do you have any other suggestions?

**Comment by swasthikcnayak** [comment]
Looks good

**Review by 18praneeth — CHANGES_REQUESTED** [review]
https://github.com/18praneeth/sushiksha-website/blob/master/templates/badge-create.html

Hey can you do the same to badge.html as we have two types of badge giving pages, this is second one

**Comment by krishnashenoy123** [comment]
> https://github.com/18praneeth/sushiksha-website/blob/master/templates/badge-create.html
> 
> Hey can you do the same to badge.html as we have two types of badge giving pages, this is second one

Yes ill do the same

**Review by 18praneeth — APPROVED** [review]

**Review by 18praneeth — APPROVED** [review]

**Pull request merged**
