### PR TITLE
Made changes to the input field in users tab

### PR DESCRIPTION
**Pull request by Gagan-Shenoy**
#18
1. Removed the highlight on input field
2. Increased the border size by 2px

### CODE REVIEW

**Comment by Gagan-Shenoy** [comment]
@venkateshprabhu2 can you please review my pr.
Thank you so much : )

**Review by 18praneeth — APPROVED** [review]
Looks good to me thank you @Gagan-Shenoy ❤️

**Comment by Gagan-Shenoy** [comment]
Thanks praneeth

**Comment by 18praneeth** [comment]
I will merge this PR after I get a confirmation from @venkateshprabhu2

**Review by venkateshprabhu2 — APPROVED** [review]

**Pull request merged**
