### PR TITLE
Minor Grammatical changes

### PR DESCRIPTION
**Pull request by srinidhibhat45**
Changes: 
line 60 : <p>Mentee</p> to <p>Mentees</p>

line 65: <p>Mentor</p> to <p>Mentors</p>

### CODE REVIEW

**Comment by venkateshprabhu2** [comment]
@srinidhibhat45 Will you be able to work on the other grammatical changes mentioned here: #5 ?

**Comment by venkateshprabhu2** [comment]
You can just add commits to your forked branch patch-1 and they will automatically get added here. You don't have to create another branch or PR.

**Review by venkateshprabhu2 — CHANGES_REQUESTED** [review]
@srinidhibhat45 Will you be able to work on the other grammatical changes mentioned here: #5 ? You can just add commits to your forked branch patch-1 and they will automatically get added here. You don't have to create another branch or PR.

**Review by 18praneeth — CHANGES_REQUESTED** [review]
@srinidhibhat45 Can you also change the tagline as mentioned in #5 and in about us section.

**Comment by 18praneeth** [comment]
The issue got resolved in #62

**Pull request closed without merging**
